export const images = {
  heroBg: "/images/hero-bg.jpg",
  heroOverlay: "/images/hero-overlay.png",
  logo: "/images/logo.png",
  logoLight: "/images/logo-light.png",
  introBride: "/images/intro-bride.jpg",
  eventsModel: "/images/events-model.jpg",
  eventsBg: "/images/events-bg.png",
  logoWatermark: "/images/logo-watermark.png",
  fabricatedBg: "/images/fabricated-bg.jpg",
  galleryHands: "/images/gallery-hands.jpg",
  gallery1: "/images/gallery-1.jpg",
  gallery2: "/images/gallery-2.jpg",
  gallery3: "/images/gallery-3.jpg",
  newbornFooter: "/images/newborn-footer.jpg",
  aboutHero: "/images/about-hero.jpg",
  aboutPortrait: "/images/about-portrait.jpg",
  aboutWatermark: "/images/about-watermark.png",
  portfolioHero: "/images/portfolio-hero.jpg",
  portfolioBanner1: "/images/portfolio-banner-1.jpg",
  portfolioBanner2: "/images/portfolio-banner-2.jpg",
  portfolioFeature: "/images/portfolio-feature.jpg",
  portfolioGalleryHero: "/images/portfolio-gallery-hero.jpg",
  servicesBg: "/images/services-bg.jpg",
  servicesWatermark: "/images/services-watermark.png",
  servicesGreen: "/images/services-green.jpg",
  servicesGold: "/images/services-gold.jpg",
  bookHeroOverlay: "/images/book-hero-overlay.png",
  bookWatermark: "/images/book-watermark.png",
  bookFabricated: "/images/book-fabricated.jpg",
  bookNewborn: "/images/book-newborn.jpg",
  portfolioGallery: [
    "/images/portfolio-01.jpg",
    "/images/portfolio-02.jpg",
    "/images/portfolio-03.jpg",
    "/images/portfolio-04.jpg",
    "/images/portfolio-05.jpg",
    "/images/portfolio-06.jpg",
    "/images/portfolio-07.jpg",
    "/images/portfolio-08.jpg",
    "/images/portfolio-09.jpg",
    "/images/portfolio-10.jpg",
    "/images/portfolio-11.jpg",
    "/images/portfolio-12.jpg",
    "/images/portfolio-13.jpg",
  ],
} as const;
