export const images = {
  herohome: "/images/heroHome.jpg",
  heroBg: "/images/hero-bg.jpg",
  heroOverlay: "/images/hero-overlay.png",
  logoBlack: "/images/logo/logoWhite.png",
  logo: "/images/logo/logoBlack.png",
  logoGreen: "/images/logo/logoGreen.png",
  logoLight: "/images/logo-light.png",
  introBride: "/images/intro-bride.jpg",
  eventsModel: "/images/events-model.jpg",
  eventsBg: "/images/events-bg.png",
  logoWatermark: "/images/logo-watermark.png",
  fabricatedBg: "/images/fabricated-bg.jpg",
  galleryHands: "/images/gallery-hands.jpg",
  gallery1: "/images/gallery-1.jpg",
  gallery2: "/images/gallery-2.jpg",
  gallery3: "/images/gallery-3.jpg",
  newbornFooter: "/images/newborn-footer.jpg",
  aboutHero: "/images/about-hero.jpg",
  aboutPortrait: "/images/about-portrait.jpg",
  aboutWatermark: "/images/about-watermark.png",
  portfolioHero: "/images/portfolio-hero.jpg",
  portfolioBanner1: "/images/portfolio-banner-1.jpg",
  portfolioBanner2: "/images/portfolio-banner-2.jpg",
  portfolioFeature: "/images/portfolio-feature.jpg",
  portfolioGalleryHero: "/images/portfolio-gallery-hero.jpg",
  servicesBg: "/images/services-bg.jpg",
  servicesWatermark: "/images/services-watermark.png",
  servicesGreen: "/images/services-green.jpg",
  servicesGold: "/images/services-gold.jpg",
  bookHeroOverlay: "/images/book-hero-overlay.png",
  bookWatermark: "/images/book-watermark.png",
  bookFabricated: "/images/book-fabricated.jpg",
  bookNewborn: "/images/book-newborn.jpg",
  aboutGallery: [
    "/images/about/1.jpeg",
    "/images/about/2.jpeg",
    "/images/about/3.jpeg",
    "/images/about/4.jpeg",
    "/images/about/5.jpeg",
    "/images/about/6.jpeg",
    "/images/about/7.jpeg",
    "/images/about/8.jpeg",
    "/images/about/9.jpeg",
    "/images/about/10.jpeg",
    "/images/about/11.jpeg",
    "/images/about/12.jpeg"
  ],
  portfolioGallery: [
    "/images/portfolio-01.jpg",
    "/images/portfolio-02.jpg",
    "/images/portfolio-03.jpg",
    "/images/portfolio-04.jpg",
    "/images/portfolio-05.jpg",
    "/images/portfolio-06.jpg",
    "/images/portfolio-07.jpg",
    "/images/portfolio-08.jpg",
    "/images/portfolio-09.jpg",
    "/images/portfolio-10.jpg",
    "/images/portfolio-11.jpg",
    "/images/portfolio-12.jpg",
    "/images/portfolio-13.jpg",
  ],
  weddingGallery: [
    "/images/wedding/1.jpeg",
    "/images/wedding/2.jpeg",
    "/images/wedding/3.jpeg",
    "/images/wedding/4.jpeg",
    "/images/wedding/5.jpeg",
    "/images/wedding/6.jpeg",
    "/images/wedding/7.jpeg",
    "/images/wedding/8.jpeg",
    "/images/wedding/9.jpeg",
    "/images/wedding/10.jpeg",
    "/images/wedding/11.jpeg",
    "/images/wedding/12.jpeg",
    "/images/wedding/12.jpeg",
    "/images/wedding/13.jpeg",
    "/images/wedding/14.jpeg",
    "/images/wedding/15.jpeg",
    "/images/wedding/16.jpeg",
    "/images/wedding/17.jpeg",
    "/images/wedding/18.jpeg",
    "/images/wedding/19.jpeg",
    "/images/wedding/20.jpeg",
    "/images/wedding/21.jpeg",
    "/images/wedding/22.jpeg",
    "/images/wedding/23.jpeg",
    "/images/wedding/24.jpeg",
    "/images/wedding/25.jpeg",
    "/images/wedding/26.jpeg",
    "/images/wedding/27.jpeg",
    "/images/wedding/28.jpeg",
    "/images/wedding/29.jpeg",
    "/images/wedding/30.jpeg",
    "/images/wedding/31.jpeg",
    "/images/wedding/32.jpeg",
    "/images/wedding/33.jpeg",
    "/images/wedding/34.jpeg"
  ],
  portraitsGallery: [
    "/images/portraits/1.jpeg",
    "/images/portraits/2.jpeg",
    "/images/portraits/3.jpeg",
    "/images/portraits/4.jpeg",
    "/images/portraits/5.jpeg",
    "/images/portraits/6.jpeg",
    "/images/portraits/7.jpeg",
    "/images/portraits/8.jpeg",
    "/images/portraits/9.jpeg",
    "/images/portraits/10.jpeg",
    "/images/portraits/11.jpeg",
    "/images/portraits/12.jpeg",
    "/images/portraits/13.jpeg",
    "/images/portraits/14.jpeg",
    "/images/portraits/15.jpeg",
    "/images/portraits/16.jpeg",
    "/images/portraits/17.jpeg",
    "/images/portraits/18.jpeg",
    "/images/portraits/19.jpeg",
    "/images/portraits/20.jpeg",
    "/images/portraits/21.jpeg",
    "/images/portraits/22.jpeg",
    "/images/portraits/23.jpeg",
    "/images/portraits/24.jpeg",
    "/images/portraits/25.jpeg",
    "/images/portraits/26.jpeg",
    "/images/portraits/27.jpeg"
  ],
  eventsGallery: [
    "/images/events/1.jpeg",
    "/images/events/2.jpeg",
    "/images/events/3.jpeg",
    "/images/events/4.jpeg",
    "/images/events/5.jpeg",
    "/images/events/6.jpeg",
    "/images/events/7.jpeg",
    "/images/events/8.jpeg",
    "/images/events/9.jpeg",
    "/images/events/10.jpeg",
    "/images/events/11.jpeg",
    "/images/events/12.jpeg",
    "/images/events/13.jpeg",
    "/images/events/14.jpeg",
    "/images/events/15.jpeg",
    "/images/events/16.jpeg",
    "/images/events/17.jpeg",
    "/images/events/18.jpeg",
    "/images/events/19.jpeg",
    "/images/events/20.jpeg",
    "/images/events/21.jpeg",
  ],
  babyShotGallery: [
    "/images/babyshoot/1.jpeg",
    "/images/babyshoot/2.jpeg",
    "/images/babyshoot/3.jpeg",
    "/images/babyshoot/4.jpeg",
    "/images/babyshoot/5.jpeg",
    "/images/babyshoot/6.jpeg",
    "/images/babyshoot/7.jpeg",
    "/images/babyshoot/8.jpeg",
    "/images/babyshoot/9.jpeg",
    "/images/babyshoot/10.jpeg",
    "/images/babyshoot/11.jpeg",
    "/images/babyshoot/12.jpeg",
    "/images/babyshoot/13.jpeg",
    "/images/babyshoot/14.jpeg",
    "/images/babyshoot/15.jpeg",
  ]
} as const;
